PATH_SCRIPT_PRODUTO        = "sql/dql/produto.sql"
PATH_UPDATE_PRODUTO        = "sql/dml/upd_produto.sql"
PATH_PARAMS_UPDATE_PRODUTO = "json/dml/upd_produto.json"

PATH_PARAMS_INS_PEDIDO_CAB = "json/dml/ins_tgfcab.json"
PATH_PARAMS_INS_PEDIDO_ITE = "json/dml/ins_tgfite.json"
PATH_PARAMS_INS_PEDIDO_FIN = "json/dml/ins_tgffin.json"
PATH_SCRIPT_PEDIDO_CAB     = "sql/dql/pedido_cab.sql"
PATH_SCRIPT_PEDIDO_ITE     = "sql/dql/pedido_ite.sql"
PATH_SCRIPT_PEDIDO_FIN     = "sql/dql/pedido_fin.sql"
PATH_INSERT_PEDIDO_CAB     = "sql/dml/ins_pedido_cab.sql"
PATH_INSERT_PEDIDO_ITE     = "sql/dml/ins_pedido_ite.sql"
PATH_INSERT_PEDIDO_FIN     = "sql/dml/ins_pedido_fin.sql"