INSERT INTO TGFVAR (
  CUSATEND,
  FIXACAO,
  NROATOCONCDRAW,
  NROMEMORANDO,
  NROREGEXPORT,
  NUNOTA,
  NUNOTAORIG,
  ORDEMPROD,
  QTDATENDIDA,
  SEQUENCIA,
  SEQUENCIAORIG,
  STATUSNOTA
) VALUES (
  :CUSATEND,
  :FIXACAO,
  :NROATOCONCDRAW,
  :NROMEMORANDO,
  :NROREGEXPORT,
  :NUNOTA,
  :NUNOTAORIG,
  :ORDEMPROD,
  :QTDATENDIDA,
  :SEQUENCIA,
  :SEQUENCIAORIG,
  :STATUSNOTA  
)