UPDATE TGFCAB
  SET DTALTER          = :DTALTER,
      VLRICMS          = :VLRICMS,
      VLRICMSDIFALDEST = :VLRICMSDIFALDEST,
      VLRICMSDIFALREM  = :VLRICMSDIFALREM,
      VLRICMSFCP       = :VLRICMSFCP,
      VLRICMSFCPINT    = :VLRICMSFCPINT
WHERE TGFCAB.NUNOTA    = :NUNOTA