SELECT EST.CODPROD, PRO.AD_MKP_IDPROD, SUM(ESTOQUE-RESERVADO) QTD
FROM TGFEST EST
    INNER JOIN TGFPRO PRO ON EST.CODPROD = PRO.CODPROD
WHERE 1=1
    AND EST.CODPROD = NVL(:P_CODPROD,EST.CODPROD)
    AND EST.CODLOCAL = 101
    AND NVL(EST.CODPARC,0) = 0
    AND EST.CODEMP IN (1,31)
    AND PRO.AD_MKP_INTEGRADO = 'S'
GROUP BY EST.CODPROD, PRO.AD_MKP_IDPROD