SELECT MAX(DHALTER) DHALTER FROM TGFTOP WHERE CODTIPOPER = :CODTIPOPER
SELECT MAX(DHALTER) DHALTER FROM TGFTPV WHERE CODTIPVENDA = :CODTIPVENDA
SELECT ULTCOD + 1 NUNOTA_NEXT FROM TGFNUM WHERE ARQUIVO = 'TGFCAB'
SELECT ULTCOD + 1 NUMNOTA_NEXT FROM TGFNUM WHERE ARQUIVO = 'PEDVEN' AND CODEMP = :CODEMP
SELECT CODCID FROM TSICID WHERE (DESCRICAOCORREIO = TRANSLATE(UPPER(:CIDADE), 'ÁÀÃÂÉÈÊÍÌÓÒÕÔÚÙÛÇ','AAAAEEEIIOOOOUUUC') OR DESCRICAOCORREIO LIKE TRANSLATE(UPPER(:CIDADE), 'ÁÀÃÂÉÈÊÍÌÓÒÕÔÚÙÛÇ','AAAAEEEIIOOOOUUUC')||'%') OR (NOMECID =    TRANSLATE(UPPER(:CIDADE), 'ÁÀÃÂÉÈÊÍÌÓÒÕÔÚÙÛÇ','AAAAEEEIIOOOOUUUC') OR NOMECID LIKE TRANSLATE(UPPER(:CIDADE), 'ÁÀÃÂÉÈÊÍÌÓÒÕÔÚÙÛÇ','AAAAEEEIIOOOOUUUC')||'%')