SELECT
    NUNOTA,
    SEQUENCIA,
    CODEMP,
    CODPROD,
    CODLOCALORIG,
    USOPROD,    
    QTDNEG,
    VLRUNIT,
    VLRTOT,    
    CODVOL,
    ATUALESTOQUE,
    RESERVA,
    STATUSNOTA,
    CODVEND
FROM TGFITE ITE    
WHERE 1=1
    AND ITE.NUNOTA = :NUNOTA
    AND ITE.SEQUENCIA = :SEQUENCIA