SELECT
    CAB.NUNOTA,
    DECODE(CAB.DTFATUR,NULL,0,1) CONFIRMADO,
    DECODE(VAR.NUNOTA,NULL,0,1) FATURADO,
    AD_MKP_CODPED,
    AD_MKP_NUMPED
FROM TGFCAB CAB
    LEFT JOIN TGFVAR VAR ON CAB.NUNOTA = VAR.NUNOTAORIG AND VAR.SEQUENCIAORIG = 1
WHERE CAB.TIPMOV = 'P' AND CAB.AD_MKP_ID = :AD_MKP_ID