SELECT
    PRO.CODPROD     AS SKU,
    INITCAP(TRIM(REPLACE(PRO.DESCRPROD,'PHALLE BEAUTY',''))) AS DESCRICAO,
    'S'             AS TIPO,
    'A'             AS SITUACAO,
    NULL            AS PRODUTO_PAI,
    PRO.CODVOL      AS UNIDADE,
    NULL            AS UNIDADE_POR_CAIXA,
    PRO.NCM         AS NCM,
    PRO.REFERENCIA  AS GTIN,
    PRO.ORIGPRO     AS ORIGEM,
    NULL            AS GARANTIA,
    NULL            AS OBSERVACOES,
    NULL            AS CATEGORIA, /* VERIFICAR */
    PRO.MARCA       AS MARCA_NOME
FROM TGFPRO PRO
WHERE 1=1
    AND PRO.CODPROD = 64410012