CREATE OR REPLACE PROCEDURE AD_STP_MKP_LANCA_ITEM_VENDA(
                    P_NUNOTA       IN  NUMBER,   -- Número único da nota
                    P_LOTE         IN  VARCHAR2, -- Lotes do produto
                    P_NUNOTA_VENDA IN  NUMBER    -- Número da nota de venda
) AS
    V_CODPROD   TGFITE.CODPROD%TYPE;
    V_QTD       TGFITE.QTDNEG%TYPE;
    V_LOTE      TGFITE.CONTROLE%TYPE;
    V_SEQUENCIA TGFITE.SEQUENCIA%TYPE;

BEGIN
    /*******************************************************************************

    @Autor: Rodrigo Vieira <rodrigo.vieira@grupoeisen.com.br>
    @Data: 13/06/2025
    @Objetivo: Lança os itens na nota a partir do pedido de venda e dos dados de lote do Olist

    ********************************************************************************/

    V_CODPROD   := REGEXP_SUBSTR(P_LOTE, '[^##]+', 1, 1);
    V_LOTE      := REGEXP_SUBSTR(P_LOTE, '[^##]+', 1, 2);
    V_QTD       := REGEXP_SUBSTR(P_LOTE, '[^##]+', 1, 3);
    SELECT NVL(MAX(SEQUENCIA), 0) + 1 INTO V_SEQUENCIA
    FROM TGFITE 
    WHERE NUNOTA = P_NUNOTA_VENDA;

    FOR PEDIDO_ITEM IN (SELECT * FROM TGFITE WHERE NUNOTA = P_NUNOTA AND CODPROD = V_CODPROD) LOOP

        AD_STP_MKP_LANCA_ITEM_TRANSF(V_CODPROD,V_LOTE,PEDIDO_ITEM.CODVOL,V_QTD);

        BEGIN
            INSERT INTO TGFITE
            (   AD_BLOQPRODPROM,
                AD_CODPRODPROM,
                AD_CODPRODPROMSUB,
                ALIQFETHAB,
                ALIQFUNTTEL,
                ALIQFUST,
                ALIQICMS,
                ALIQICMSAT,
                ALIQICMSRED,
                ALIQINTERICMSAT,
                ALIQIPI,
                ALIQISS,
                ALIQSTEXTRANOTA,
                ALIQSTFCPSTANT,
                ALTPRECO,
                ALTURA,
                ATUALESTOQUE,
                ATUALESTTERC,
                BASECALCSTEXTRANOTA,
                BASEFUNTTEL,
                BASEFUST,
                BASEICMS,
                BASEICMSAT,
                BASEICMSSTFRETE,
                BASEIPI,
                BASEISS,
                BASESTANT,
                BASESTEXTRANOTA,
                BASESTFCPINTANT,
                BASESTUFDEST,
                BASESUBSTIT,
                BASESUBSTITANT,
                BASESUBSTITUNITORIG,
                BASESUBSTSEMRED,
                BASICMMOD,
                BASICMSTMOD,
                CNPJFABRICANTE,
                CODAGREGACAO,
                CODANTECIPST,
                CODBARRAPDV,
                CODBENEFNAUF,
                CODCAV,
                CODCFO,
                CODCFPS,
                CODDOCARRECAD,
                CODEMP,
                CODENQIPI,
                CODESPECST,
                CODEXEC,
                CODFCI,
                CODIGONFCOM,
                CODIPI,
                CODLOCALORIG,
                CODLOCALTERC,
                CODMOTDESONERAICMS,
                CODMOTDESONERAST,
                CODNATREND,
                CODOBSPADRAO,
                CODPARCEXEC,
                CODPROC,
                CODPROD,
                CODPROMO,
                CODSIT08EFD,
                CODTPA,
                CODTRIB,
                CODTRIBISS,
                CODUSU,
                CODVEND,
                CODVOL,
                CODVOLPARC,
                CONTROLE,
                CSOSN,
                CSTIPI,
                CUSTO,
                DTALTER,
                DTINICIO,
                ENDIMAGEM,
                ESPESSURA,
                FATURAR,
                GERAPRODUCAO,
                GRUPOTRANSG,
                GTINNFE,
                GTINTRIBNFE,
                ICMSSTFRETE,
                IDALIQICMS,
                IDALIQICMSAT,
                IDALIQICMSDIFICMS,
                IDALIQISS,
                IDDESCPARCERIA,
                INDDEVOLUCAONFCOM,
                INDESCALA,
                INDREPDES,
                LARGURA,
                M3,
                MARGLUCRO,
                NRSERIERESERVA,
                NUFOP,
                NUMCONTRATO,
                NUMDOCARRECAD,
                NUMEROOS,
                NUMPEDIDO2,
                NUNOTA,
                NUPROMOCAO,
                NUTAB,
                OBSERVACAO,
                ORIGEMBUSCA,
                ORIGPROD,
                PENDENTE,
                PERCCOM,
                PERCCOMGER,
                PERCDESC,
                PERCDESCBASE,
                PERCDESCBONIF,
                PERCDESCDIGITADO,
                PERCDESCFORNECEDOR,
                PERCDESCPROM,
                PERCDESCTGFDES,
                PERCGERMIN,
                PERCPUREZA,
                PERCREDVLRIPI,
                PERCSTFCPINTANT,
                PERCUSAQUDECPE,
                PERCUSAQUDECPEEST,
                PRECOBASE,
                PRECOBASEQTD,
                PRODUTONFE,
                PRODUTOPESQUISADO,
                QTDCONFERIDA,
                QTDENTREGUE,
                QTDFAT,
                QTDFIXADA,
                QTDFORMULA,
                QTDNEG,
                QTDPECA,
                QTDTRIBEXPORT,
                QTDVOL,
                QTDWMS,
                REDBASEST,
                RESERVA,
                SEQPEDIDO2,
                SEQUENCIA,
                SEQUENCIAFISCAL,
                SOLCOMPRA,
                STATUSLOTE,
                STATUSNOTA,
                TERCEIROS,
                TIPENTREGA,
                TIPOSEPARACAO,
                TIPUTILCOM,
                UNIDADE,
                USOPROD,
                VARIACAOFCP,
                VLRACRESCDESC,
                VLRCOM,
                VLRCOMGER,
                VLRCUS,
                VLRCUSAQUDECPE,
                VLRDESC,
                VLRDESCBONIF,
                VLRDESCDIGITADO,
                VLRDESCMOE,
                VLRDESCPARCERIA,
                VLRFETHAB,
                VLRFUNTTEL,
                VLRFUST,
                VLRICMS,
                VLRICMSANT,
                VLRICMSAT,
                VLRICMSDIFERIDO,
                VLRICMSUFDEST,
                VLRIPI,
                VLRISS,
                VLRLIQPROM,
                VLRPROMO,
                VLRPTOPUREZA,
                VLRREPRED,
                VLRREPREDSEMDESC,
                VLRREPREDST,
                VLRRETENCAO,
                VLRSTEXTRANOTA,
                VLRSTFCPINTANT,
                VLRSUBST,
                VLRSUBSTANT,
                VLRSUBSTUNITORIG,
                VLRTOT,
                VLRTOTMOE,
                VLRTROCA,
                VLRUNIT,
                VLRUNITDOLAR,
                VLRUNITLOC,
                VLRUNITMOE,
                VLRVENDAPROMO
            ) VALUES (
                PEDIDO_ITEM.AD_BLOQPRODPROM,
                PEDIDO_ITEM.AD_CODPRODPROM,
                PEDIDO_ITEM.AD_CODPRODPROMSUB,
                PEDIDO_ITEM.ALIQFETHAB,
                PEDIDO_ITEM.ALIQFUNTTEL,
                PEDIDO_ITEM.ALIQFUST,
                PEDIDO_ITEM.ALIQICMS,
                PEDIDO_ITEM.ALIQICMSAT,
                PEDIDO_ITEM.ALIQICMSRED,
                PEDIDO_ITEM.ALIQINTERICMSAT,
                PEDIDO_ITEM.ALIQIPI,
                PEDIDO_ITEM.ALIQISS,
                PEDIDO_ITEM.ALIQSTEXTRANOTA,
                PEDIDO_ITEM.ALIQSTFCPSTANT,
                PEDIDO_ITEM.ALTPRECO,
                PEDIDO_ITEM.ALTURA,
                -1, -- ATUALESTOQUE
                PEDIDO_ITEM.ATUALESTTERC,
                PEDIDO_ITEM.BASECALCSTEXTRANOTA,
                PEDIDO_ITEM.BASEFUNTTEL,
                PEDIDO_ITEM.BASEFUST,
                PEDIDO_ITEM.BASEICMS,
                PEDIDO_ITEM.BASEICMSAT,
                PEDIDO_ITEM.BASEICMSSTFRETE,
                PEDIDO_ITEM.BASEIPI,
                PEDIDO_ITEM.BASEISS,
                PEDIDO_ITEM.BASESTANT,
                PEDIDO_ITEM.BASESTEXTRANOTA,
                PEDIDO_ITEM.BASESTFCPINTANT,
                PEDIDO_ITEM.BASESTUFDEST,
                PEDIDO_ITEM.BASESUBSTIT,
                PEDIDO_ITEM.BASESUBSTITANT,
                PEDIDO_ITEM.BASESUBSTITUNITORIG,
                PEDIDO_ITEM.BASESUBSTSEMRED,
                PEDIDO_ITEM.BASICMMOD,
                PEDIDO_ITEM.BASICMSTMOD,
                PEDIDO_ITEM.CNPJFABRICANTE,
                PEDIDO_ITEM.CODAGREGACAO,
                PEDIDO_ITEM.CODANTECIPST,
                PEDIDO_ITEM.CODBARRAPDV,
                PEDIDO_ITEM.CODBENEFNAUF,
                PEDIDO_ITEM.CODCAV,
                (SELECT NVL(CASE WHEN CID.UF = 15 THEN TOP.CODCFO_SAIDA ELSE TOP.CODCFO_SAIDA_FORA END,0) AS CODCFO
                FROM TGFCAB CAB INNER JOIN TGFTOP TOP ON TOP.CODTIPOPER = CAB.CODTIPOPER AND TOP.DHALTER = CAB.DHTIPOPER
                                INNER JOIN TSICID CID ON CAB.AD_MKP_DESTINO = CID.CODCID
                WHERE CAB.NUNOTA = P_NUNOTA_VENDA), --CODCFO
                PEDIDO_ITEM.CODCFPS,
                PEDIDO_ITEM.CODDOCARRECAD,
                PEDIDO_ITEM.CODEMP,
                PEDIDO_ITEM.CODENQIPI,
                PEDIDO_ITEM.CODESPECST,
                PEDIDO_ITEM.CODEXEC,
                PEDIDO_ITEM.CODFCI,
                PEDIDO_ITEM.CODIGONFCOM,
                PEDIDO_ITEM.CODIPI,
                PEDIDO_ITEM.CODLOCALORIG,
                PEDIDO_ITEM.CODLOCALTERC,
                PEDIDO_ITEM.CODMOTDESONERAICMS,
                PEDIDO_ITEM.CODMOTDESONERAST,
                PEDIDO_ITEM.CODNATREND,
                PEDIDO_ITEM.CODOBSPADRAO,
                PEDIDO_ITEM.CODPARCEXEC,
                PEDIDO_ITEM.CODPROC,
                PEDIDO_ITEM.CODPROD,
                PEDIDO_ITEM.CODPROMO,
                'N', -- CODSIT08EFD
                PEDIDO_ITEM.CODTPA,
                PEDIDO_ITEM.CODTRIB,
                PEDIDO_ITEM.CODTRIBISS,
                PEDIDO_ITEM.CODUSU,
                PEDIDO_ITEM.CODVEND,
                PEDIDO_ITEM.CODVOL,
                PEDIDO_ITEM.CODVOLPARC,
                V_LOTE, -- CONTROLE
                PEDIDO_ITEM.CSOSN,
                PEDIDO_ITEM.CSTIPI,
                PEDIDO_ITEM.CUSTO,
                SYSDATE, -- DTALTER
                PEDIDO_ITEM.DTINICIO,
                PEDIDO_ITEM.ENDIMAGEM,
                PEDIDO_ITEM.ESPESSURA,
                PEDIDO_ITEM.FATURAR,
                PEDIDO_ITEM.GERAPRODUCAO,
                PEDIDO_ITEM.GRUPOTRANSG,
                PEDIDO_ITEM.GTINNFE,
                PEDIDO_ITEM.GTINTRIBNFE,
                PEDIDO_ITEM.ICMSSTFRETE,
                PEDIDO_ITEM.IDALIQICMS,
                PEDIDO_ITEM.IDALIQICMSAT,
                PEDIDO_ITEM.IDALIQICMSDIFICMS,
                PEDIDO_ITEM.IDALIQISS,
                PEDIDO_ITEM.IDDESCPARCERIA,
                PEDIDO_ITEM.INDDEVOLUCAONFCOM,
                PEDIDO_ITEM.INDESCALA,
                PEDIDO_ITEM.INDREPDES,
                PEDIDO_ITEM.LARGURA,
                PEDIDO_ITEM.M3,
                PEDIDO_ITEM.MARGLUCRO,
                PEDIDO_ITEM.NRSERIERESERVA,
                PEDIDO_ITEM.NUFOP,
                PEDIDO_ITEM.NUMCONTRATO,
                PEDIDO_ITEM.NUMDOCARRECAD,
                PEDIDO_ITEM.NUMEROOS,
                PEDIDO_ITEM.NUMPEDIDO2,
                P_NUNOTA_VENDA, -- NUNOTA
                PEDIDO_ITEM.NUPROMOCAO,
                PEDIDO_ITEM.NUTAB,
                PEDIDO_ITEM.OBSERVACAO,
                PEDIDO_ITEM.ORIGEMBUSCA,
                PEDIDO_ITEM.ORIGPROD,
                PEDIDO_ITEM.PENDENTE,
                PEDIDO_ITEM.PERCCOM,
                PEDIDO_ITEM.PERCCOMGER,
                PEDIDO_ITEM.PERCDESC,
                PEDIDO_ITEM.PERCDESCBASE,
                PEDIDO_ITEM.PERCDESCBONIF,
                PEDIDO_ITEM.PERCDESCDIGITADO,
                PEDIDO_ITEM.PERCDESCFORNECEDOR,
                PEDIDO_ITEM.PERCDESCPROM,
                PEDIDO_ITEM.PERCDESCTGFDES,
                PEDIDO_ITEM.PERCGERMIN,
                PEDIDO_ITEM.PERCPUREZA,
                PEDIDO_ITEM.PERCREDVLRIPI,
                PEDIDO_ITEM.PERCSTFCPINTANT,
                PEDIDO_ITEM.PERCUSAQUDECPE,
                PEDIDO_ITEM.PERCUSAQUDECPEEST,
                PEDIDO_ITEM.PRECOBASE,
                PEDIDO_ITEM.PRECOBASEQTD,
                PEDIDO_ITEM.PRODUTONFE,
                PEDIDO_ITEM.PRODUTOPESQUISADO,
                V_QTD, -- QTDCONFERIDA
                PEDIDO_ITEM.QTDENTREGUE,
                PEDIDO_ITEM.QTDFAT,
                PEDIDO_ITEM.QTDFIXADA,
                PEDIDO_ITEM.QTDFORMULA,
                V_QTD, --QTDNEG,
                PEDIDO_ITEM.QTDPECA,
                PEDIDO_ITEM.QTDTRIBEXPORT,
                PEDIDO_ITEM.QTDVOL,
                PEDIDO_ITEM.QTDWMS,
                PEDIDO_ITEM.REDBASEST,
                'N', -- RESERVA
                PEDIDO_ITEM.SEQPEDIDO2,
                V_SEQUENCIA, -- SEQUENCIA
                V_SEQUENCIA, -- SEQUENCIAFISCAL
                'N', -- SOLCOMPRA
                'N', -- STATUSLOTE
                'A', -- STATUSNOTA
                PEDIDO_ITEM.TERCEIROS,
                PEDIDO_ITEM.TIPENTREGA,
                PEDIDO_ITEM.TIPOSEPARACAO,
                PEDIDO_ITEM.TIPUTILCOM,
                PEDIDO_ITEM.UNIDADE,
                PEDIDO_ITEM.USOPROD,
                PEDIDO_ITEM.VARIACAOFCP,
                PEDIDO_ITEM.VLRACRESCDESC,
                PEDIDO_ITEM.VLRCOM,
                PEDIDO_ITEM.VLRCOMGER,
                PEDIDO_ITEM.VLRCUS,
                PEDIDO_ITEM.VLRCUSAQUDECPE,
                PEDIDO_ITEM.VLRDESC,
                PEDIDO_ITEM.VLRDESCBONIF,
                PEDIDO_ITEM.VLRDESCDIGITADO,
                PEDIDO_ITEM.VLRDESCMOE,
                PEDIDO_ITEM.VLRDESCPARCERIA,
                PEDIDO_ITEM.VLRFETHAB,
                PEDIDO_ITEM.VLRFUNTTEL,
                PEDIDO_ITEM.VLRFUST,
                PEDIDO_ITEM.VLRICMS,
                PEDIDO_ITEM.VLRICMSANT,
                PEDIDO_ITEM.VLRICMSAT,
                PEDIDO_ITEM.VLRICMSDIFERIDO,
                PEDIDO_ITEM.VLRICMSUFDEST,
                PEDIDO_ITEM.VLRIPI,
                PEDIDO_ITEM.VLRISS,
                PEDIDO_ITEM.VLRLIQPROM,
                PEDIDO_ITEM.VLRPROMO,
                PEDIDO_ITEM.VLRPTOPUREZA,
                PEDIDO_ITEM.VLRREPRED,
                PEDIDO_ITEM.VLRREPREDSEMDESC,
                PEDIDO_ITEM.VLRREPREDST,
                PEDIDO_ITEM.VLRRETENCAO,
                PEDIDO_ITEM.VLRSTEXTRANOTA,
                PEDIDO_ITEM.VLRSTFCPINTANT,
                PEDIDO_ITEM.VLRSUBST,
                PEDIDO_ITEM.VLRSUBSTANT,
                PEDIDO_ITEM.VLRSUBSTUNITORIG,
                ROUND(PEDIDO_ITEM.VLRUNIT * V_QTD, 3), -- VLRTOT
                PEDIDO_ITEM.VLRTOTMOE,
                PEDIDO_ITEM.VLRTROCA,
                PEDIDO_ITEM.VLRUNIT,
                PEDIDO_ITEM.VLRUNITDOLAR,
                PEDIDO_ITEM.VLRUNITLOC,
                PEDIDO_ITEM.VLRUNITMOE,
                PEDIDO_ITEM.VLRVENDAPROMO   
            );
        END;
    END LOOP;
END;