CREATE OR REPLACE PROCEDURE AD_STP_MKP_LANCA_IMP_VENDA(P_NUNOTA IN NUMBER) -- Número único da nota
AS V_COUNT NUMBER;  
BEGIN
    /*******************************************************************************

    @Autor: Rodrigo Vieira <rodrigo.vieira@grupoeisen.com.br>
    @Data: 01/07/2025
    @Objetivo: Lança os impostos da nota a partir do pedido de venda

    ********************************************************************************/
    -- COPIANDO IMPOSTOS DO PEDIDO PARA NOTA
    FOR PEDIDO_IMP IN (
        SELECT
            DIN.ALIQDESPACESS,
            DIN.ALIQDIFERENCIAL,
            DIN.ALIQINTDEST,
            DIN.ALIQPARADIFAL,
            DIN.ALIQUOTA,
            DIN.ALIQUOTADESON,
            DIN.ALIQUOTAEFET,
            DIN.ALIQUOTANORMAL,
            DIN.BASE,
            DIN.BASEDIFAL,
            DIN.BASEFCP,
            DIN.BASEFCPINT,
            DIN.BASENORMDIFICMS,
            DIN.BASERED,
            DIN.BASEREDEFET,
            DIN.CODBEN,
            DIN.CODIMP,
            DIN.CODINC,
            DIN.CODLST,
            DIN.CODNATREND,
            DIN.CODTRIBMUNISS,
            DIN.CODUSU,
            DIN.COMIVA,
            DIN.CST,
            DIN.DIGITADO,
            DIN.IDALIQ,
            DIN.IVA,
            DIN.MOTREDADREM,
            VAR.NUNOTA,
            DIN.PAUTA,
            DIN.PERCALIQADREMICMS,
            DIN.PERCFCP,
            DIN.PERCFCPINT,
            DIN.PERCINSSESPECIAL,
            DIN.PERCPARTDIFAL,
            DIN.PERCREDBASE,
            DIN.PERCREDBASEEFET,
            DIN.PERCREDPR,
            DIN.PERCREDVLRIPI,
            DIN.PERCVLR,
            DIN.RETEMFIN,
            VAR.SEQUENCIAORIG,
            VAR.SEQUENCIA,
            DIN.TIPCALCDIFAL,
            DIN.TIPCALCFCPESPEC,
            DIN.TIPO,
            DIN.TIPODEDISS,
            DIN.TIPOINSSESPECIAL,
            DIN.TPIRRFEXT,
            DIN.VALOR,
            DIN.VALORDESON,
            DIN.VALORDIFERENCIAL,
            DIN.VALOREFET,
            DIN.VLRCRED,
            DIN.VLRCREDPR,
            DIN.VLRDIFALDEST,
            DIN.VLRDIFALREM,
            DIN.VLRFCP,
            DIN.VLRFCPINT,
            DIN.VLRICMSMONODEV,
            DIN.VLRICMSMONODIF,
            DIN.VLRICMSPARADIFAL,
            DIN.VLRINSSESPECIAL,
            DIN.VLRREPDIFALFCP,
            DIN.VLRREPRED,
            DIN.VLRREPREDSEMDESC
        FROM TGFDIN DIN
            INNER JOIN TGFVAR VAR ON DIN.NUNOTA = VAR.NUNOTAORIG AND DIN.SEQUENCIA = VAR.SEQUENCIAORIG
        WHERE DIN.NUNOTA = P_NUNOTA        
    ) LOOP
        SELECT COUNT(*)
        INTO V_COUNT
        FROM TGFVAR 
        WHERE NUNOTAORIG = P_NUNOTA AND SEQUENCIAORIG = PEDIDO_IMP.SEQUENCIAORIG;
        
        BEGIN
            INSERT INTO TGFDIN (
                ALIQDESPACESS,
                ALIQDIFERENCIAL,
                ALIQINTDEST,
                ALIQPARADIFAL,
                ALIQUOTA,
                ALIQUOTADESON,
                ALIQUOTAEFET,
                ALIQUOTANORMAL,
                BASE,
                BASEDIFAL,
                BASEFCP,
                BASEFCPINT,
                BASENORMDIFICMS,
                BASERED,
                BASEREDEFET,
                CODBEN,
                CODIMP,
                CODINC,
                CODLST,
                CODNATREND,
                CODTRIBMUNISS,
                CODUSU,
                COMIVA,
                CST,
                DHALTER,
                DIGITADO,
                IDALIQ,
                IVA,
                MOTREDADREM,
                NUNOTA,
                PAUTA,
                PERCALIQADREMICMS,
                PERCFCP,
                PERCFCPINT,
                PERCINSSESPECIAL,
                PERCPARTDIFAL,
                PERCREDBASE,
                PERCREDBASEEFET,
                PERCREDPR,
                PERCREDVLRIPI,
                PERCVLR,
                RETEMFIN,
                SEQUENCIA,
                TIPCALCDIFAL,
                TIPCALCFCPESPEC,
                TIPO,
                TIPODEDISS,
                TIPOINSSESPECIAL,
                TPIRRFEXT,
                VALOR,
                VALORDESON,
                VALORDIFERENCIAL,
                VALOREFET,
                VLRCRED,
                VLRCREDPR,
                VLRDIFALDEST,
                VLRDIFALREM,
                VLRFCP,
                VLRFCPINT,
                VLRICMSMONODEV,
                VLRICMSMONODIF,
                VLRICMSPARADIFAL,
                VLRINSSESPECIAL,
                VLRREPDIFALFCP,
                VLRREPRED,
                VLRREPREDSEMDESC
            ) VALUES (
                ROUND(NVL(PEDIDO_IMP.ALIQDESPACESS,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.ALIQDIFERENCIAL,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.ALIQINTDEST,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.ALIQPARADIFAL,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.ALIQUOTA,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.ALIQUOTADESON,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.ALIQUOTAEFET,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.ALIQUOTANORMAL,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.BASE,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.BASEDIFAL,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.BASEFCP,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.BASEFCPINT,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.BASENORMDIFICMS,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.BASERED,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.BASEREDEFET,0) / V_COUNT,3),
                PEDIDO_IMP.CODBEN,
                PEDIDO_IMP.CODIMP,
                PEDIDO_IMP.CODINC,
                PEDIDO_IMP.CODLST,
                PEDIDO_IMP.CODNATREND,
                PEDIDO_IMP.CODTRIBMUNISS,
                PEDIDO_IMP.CODUSU,
                PEDIDO_IMP.COMIVA,
                PEDIDO_IMP.CST,
                SYSDATE, -- DHALTER
                PEDIDO_IMP.DIGITADO,
                PEDIDO_IMP.IDALIQ,
                PEDIDO_IMP.IVA,
                PEDIDO_IMP.MOTREDADREM,
                PEDIDO_IMP.NUNOTA,
                PEDIDO_IMP.PAUTA,
                PEDIDO_IMP.PERCALIQADREMICMS,
                PEDIDO_IMP.PERCFCP,
                PEDIDO_IMP.PERCFCPINT,
                PEDIDO_IMP.PERCINSSESPECIAL,
                PEDIDO_IMP.PERCPARTDIFAL,
                PEDIDO_IMP.PERCREDBASE,
                PEDIDO_IMP.PERCREDBASEEFET,
                PEDIDO_IMP.PERCREDPR,
                PEDIDO_IMP.PERCREDVLRIPI,
                PEDIDO_IMP.PERCVLR,
                PEDIDO_IMP.RETEMFIN,
                PEDIDO_IMP.SEQUENCIA,
                PEDIDO_IMP.TIPCALCDIFAL,
                PEDIDO_IMP.TIPCALCFCPESPEC,
                PEDIDO_IMP.TIPO,
                PEDIDO_IMP.TIPODEDISS,
                PEDIDO_IMP.TIPOINSSESPECIAL,
                PEDIDO_IMP.TPIRRFEXT,
                ROUND(NVL(PEDIDO_IMP.VALOR,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.VALORDESON,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.VALORDIFERENCIAL,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.VALOREFET,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.VLRCRED,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.VLRCREDPR,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.VLRDIFALDEST,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.VLRDIFALREM,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.VLRFCP,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.VLRFCPINT,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.VLRICMSMONODEV,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.VLRICMSMONODIF,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.VLRICMSPARADIFAL,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.VLRINSSESPECIAL,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.VLRREPDIFALFCP,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.VLRREPRED,0) / V_COUNT,3),
                ROUND(NVL(PEDIDO_IMP.VLRREPREDSEMDESC,0) / V_COUNT,3)
            );
        END;
    END LOOP;

END;